airflow.datalake.net
*** Found local files:
***   * /opt/airflow/logs/dag_id=fharenheit/run_id=manual__2024-05-19T07:14:22.073216+00:00/task_id=get_previous_success_timestamp/attempt=1.log
[2024-05-19T16:14:23.127+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T16:14:23.162+0900] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fharenheit.get_previous_success_timestamp manual__2024-05-19T07:14:22.073216+00:00 [queued]>
[2024-05-19T16:14:23.169+0900] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fharenheit.get_previous_success_timestamp manual__2024-05-19T07:14:22.073216+00:00 [queued]>
[2024-05-19T16:14:23.170+0900] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-19T16:14:23.180+0900] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_previous_success_timestamp> on 2024-05-19 07:14:22.073216+00:00
[2024-05-19T16:14:23.186+0900] {standard_task_runner.py:63} INFO - Started process 57757 to run task
[2024-05-19T16:14:23.194+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'fharenheit', 'get_previous_success_timestamp', 'manual__2024-05-19T07:14:22.073216+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/fharenheit.py', '--cfg-path', '/tmp/tmpbcsupb85']
[2024-05-19T16:14:23.195+0900] {standard_task_runner.py:91} INFO - Job 111: Subtask get_previous_success_timestamp
[2024-05-19T16:14:23.272+0900] {task_command.py:426} INFO - Running <TaskInstance: fharenheit.get_previous_success_timestamp manual__2024-05-19T07:14:22.073216+00:00 [running]> on host airflow.datalake.net
[2024-05-19T16:14:23.369+0900] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fharenheit' AIRFLOW_CTX_TASK_ID='get_previous_success_timestamp' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T07:14:22.073216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T07:14:22.073216+00:00'
[2024-05-19T16:14:23.370+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T16:14:23.371+0900] {logging_mixin.py:188} INFO - Context에서 값을 출
[2024-05-19T16:14:23.371+0900] {logging_mixin.py:188} INFO - 2024-05-19 07:04:08.693537+00:00
[2024-05-19T16:14:23.371+0900] {logging_mixin.py:188} INFO - <class 'pendulum.datetime.DateTime'>
[2024-05-19T16:14:23.371+0900] {python.py:237} INFO - Done. Returned value was: 2024-05-19 07:04:08.693537+00:00
[2024-05-19T16:14:23.372+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T16:14:23.402+0900] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fharenheit, task_id=get_previous_success_timestamp, execution_date=20240519T071422, start_date=20240519T071423, end_date=20240519T071423
[2024-05-19T16:14:23.430+0900] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T16:14:23.452+0900] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T16:14:23.453+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
